apps:
  - name: app
    script: ./index.js
    exec_mode: cluster
    instances: max
    watch: false
    max_memory_restart: 100M
    exp_backoff_restart_delay: 100
    env_prod:
      ENVIRONMENT: PRODUCTION
    env_homolog:
      ENVIRONMENT: HOMOLOG